### ISSUE TITLE
 Reddconomy Frontend (sponge) - Implement external QR

### ISSUE THREAD

**Issue by riccardobl** [Reddconomy/Reddconomy#7]
Current chat based QR code has some major limitations: it might be hard to catch when many users are sending chat messages, it requires a manual tweak to the options file to enlarge the chat, sometimes it's hard to read for the devices due to the colors of the background environment.

An optional setting to generate a clickable link to an external qr should be added.

**Comment by Soxasora** [comment]
[Done here](https://github.com/Reddconomy/Reddconomy/commit/f3504940f3da3a27f85b4321e9a188af7a5f882e)
