### ISSUE TITLE
 Reddconomy Frontend (sponge) - plugin/ReddconomyApi is inconsistent

### ISSUE THREAD

**Issue by riccardobl** [Reddconomy/Reddconomy#8]
All methods should use either long values or double values, not a mix of the two.

**Comment by Soxasora** [comment]
ReddconomyApi methods that requests "amount" now only takes long types.
CreateQR has been moved to Utils because it's not a ReddconomyApi.
[More info here](https://github.com/Reddconomy/Reddconomy/commit/bcf05d713c9dd1853cb1d9d97bae5c395fb34056)
